"""remove user foreign key

Revision ID: d6da8968811c
Revises: 7cbe62b8e1f8
Create Date: 2026-06-22 11:40:02.049136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6da8968811c'
down_revision: Union[str, Sequence[str], None] = '7cbe62b8e1f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('entries_user_id_fkey'), 'entries', type_='foreignkey')
    op.drop_column('entries', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('entries_user_id_fkey'), 'entries', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
