"""add created_at to entries

Revision ID: 7cbe62b8e1f8
Revises: d19dc65eb757
Create Date: 2026-06-22 11:18:18.713018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbe62b8e1f8'
down_revision: Union[str, Sequence[str], None] = 'd19dc65eb757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('entries', 'created_at')
    # ### end Alembic commands ###
